### ISSUE TITLE
Make a better looking print preview dialog

### ISSUE THREAD

**Issue by yevgeni-zolotko** [alternetsoft/AlternetUI#1]
Buttons are two big in the preview dialog on High DPI
![image](https://user-images.githubusercontent.com/64135073/199224596-d9fd5bf4-d968-461e-840b-f9f34bc3b505.png)

 OS does not provide its own preview dialogs. That's the one implemented by wxwidgets.

![image](https://user-images.githubusercontent.com/64135073/199224679-13c1ab78-a568-4fad-a597-6bb9d52223ba.png)

**Comment by generalloki** [comment]
And on my high dpi display print preview is too small. I speak not only about buttons (they seem to be ok) but the printed document. It looks like small on 100%

**Comment by generalloki** [comment]
Print Preview dialog seems to be ok (at least buttons in toolbar look fine on high dpi). So I am closing this issue
