### ISSUE TITLE
Enhancement : Bitmap contructor with url param

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#124]
@generalloki 

Thanks to add this option like native .Net.

In .Net, you can use : 
Bitmap bm = new Bitmap("Test.jpg");

In AlternetUI, you must specified a path like this : 
Bitmap bm = new Bitmap(PathUtils.GetAppFolder() + "Test.jpg");

Can you add code to verify if a path was given or not and if not, test if file exist in PathUtils.GetAppFolder() to open it ?

Thanks

**Comment by generalloki** [comment]
Great idea. I will do this.

**Comment by generalloki** [comment]
Done in Master

**Comment by neoxeo** [comment]
Test Ok, perfect !

Thanks a lot
