### ISSUE TITLE
Update documentation to use new DocFX

### ISSUE THREAD

**Issue by generalloki** [alternetsoft/AlternetUI#17]
Need to fix the newest version of docfx and see if it performs better.

**Comment by generalloki** [comment]
We updated documentation to use latest DocFx version. Next week new docs will be uploaded to docs web site.  So for now I am closing this issue.

**Comment by neoxeo** [comment]
@generalloki 

If I translate the 8500 generated html files in french, do you think it can be useful or not ?

**Comment by generalloki** [comment]
@neoxeo , I beleive English version is enough. Also documentation is updated with the each release.

**Comment by generalloki** [comment]
New documentation generated with new DocFX is uploaded.
