### ISSUE TITLE
Improvement : UiXML Designer

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#36]
It will be fantastic if we can have a Designer like this : 
https://github.com/icsharpcode/WpfDesigner

**Comment by generalloki** [comment]
We have our own designer for WinForms. Probably we will be using it if we decide to develop full featured form designer for UiXML. We will study WpfDesigner.  Now we are adding new controls and implement bug fixes for the existing controls, form designer is not the priority now.

**Comment by neoxeo** [comment]
@generalloki 

I don't know if it's a hard task to "convert" Alternet Studio FormDesigner.Wpf project to create a new AlternetUI sample with a light version of it. 
I know you have a lot of work but it would be a very good point to convain people to test and adpot AlternetUI.

Thanks a lot, again for all of your job !

**Comment by generalloki** [comment]
@neoxeo 

Current situation is the following:

We are working on the cross-platform version of the Editor and Scripter, which will be ported to Alternet.UI as well.  We sure want to have cross-platform Designer version. Priority is Editor, than Scripter, after that Designer. I will post here any updates on this issue.

**Comment by generalloki** [comment]
For now I am closing this issue. We could reopen it in future.
