### ISSUE TITLE
WebBrower problem after resize

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#47]
In samples/WebBrowser : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/72fc8531-341f-4aff-a159-1e756a1a809c)

How to reproduce : 
Open ControlsSample 
Click on WebBrowser
Click, on full size button ![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/56c5db44-a3a3-4c81-9719-d84213eb63f4)

**Comment by generalloki** [comment]
@neoxeo What is you operating system version? I don't see this problem on Win11

**Comment by neoxeo** [comment]
Infos for Msinfo : 
![Uploading image.png…]()

**Comment by neoxeo** [comment]
Strange thing : this error is present only if I was in debug mode into VS2022. I f I run compiled ControlsSample.exe, I can't reproduce this probem

**Comment by neoxeo** [comment]
Sunday (when I will have a correct network), I will update video driver to see if it solve problem or not. I have actually Nvidia 528.90.

**Comment by neoxeo** [comment]
Test with 536.67 version of Nvidia drivers and VS2022 version 17.7 Preview 5 and commit a24bc2c92575b36dcd5e992c5c6dfa8cdb33b75a and .Net7.0.9 : always KO

But if I put my mouse at the "empty place", down arrow show again. This is true before and after updates.

**Comment by neoxeo** [comment]
@generalloki 

Tested with ee6e0ce897070fb8b6ae6164b230441a4653bf90 version. Issue solved (I think it was solved for a long time but I can't say when)
