### ISSUE TITLE
Add RichTextBox

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#49]
In this topic we collect all issues related to RichEdit functionality.

**Comment by neoxeo** [comment]
@generalloki, thanks for all new "functions" available for TextBox and Sample added into Text Input

**Comment by dmitry-medvedev** [comment]
May be we need to create a separate control like RichTextBox (and just set IsRichEdit = true in the constructor)?

**Comment by generalloki** [comment]
This is good idea. But first we need to study difference between 
wxRichTextCtrl (https://docs.wxwidgets.org/3.2/classwx_rich_text_ctrl.html)
and wxTextCtrl in rich edit mode. Also we need to study whether wxRichTextCtrl/wxTextCtrl
has file save/open feature in rich text format.

**Comment by dmitry-medvedev** [comment]
sounds good, wxRichTextCtrl may provide extra features, need to be investigated.

**Comment by generalloki** [comment]
I am closing this issue for now as fully featured RichTextBox is implemented
