### ISSUE TITLE
Input Sample question 

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#52]
For mouse, capture must work only here ? 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/25e6ce0c-0fdd-4c30-afdd-1469f5903d5a)

Because, capture works on all the form

**Comment by generalloki** [comment]
I beleive mouse events are propagnated to contol's parent, so they go to all the parent controls if are not handled in the control. So, I beleive it is supposed to be so. "Capture" here is to get events even if mouse is outside the control.  So I am closing this issue as it seems to be like expected..
