### ISSUE TITLE
Error with Install.bat with f2b74712c07f3f15f4cbadfbdf8f5bb8a8a62d5e

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#56]
@generalloki 

Il have pull last version f2b74712c07f3f15f4cbadfbdf8f5bb8a8a62d5e and run install.bat : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/7aaa4ec3-61eb-469c-b16c-3a332990f1bf)

File is present here : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/0805e9cb-064a-48ef-9a5c-dfb8baa6d124)

On linux, Install.sh is OK

**Comment by generalloki** [comment]
Fixed in master.

**Comment by generalloki** [comment]
@neoxeo , Thanks for reporting this issue!!!
