### ISSUE TITLE
Error with install.bat

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#57]
@generalloki 

Thanks a lot to solve very quickly issue #56 

New Errors with 7c88d4cfe18e2bf3aa655bf252169600e27f683a version : 

![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/1dcb1fcc-39fb-412f-b032-02e98151e59c)

**Comment by generalloki** [comment]
@neoxeo , Thanks! I have updated master with the fix.

**Comment by neoxeo** [comment]
@generalloki 

New error with install.bat on branch AlternetUI-MasterWithWebBrowser with 0bce38540953f43fc834780d99e64ce4f32c748c version
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/c940fd45-2e15-4a07-ba32-8b383d3e4aba)

**Comment by generalloki** [comment]
@neoxeo , I executed Install.bat just now and it works fine on my pc. Could you please rerun it on the latest version of master or MasterWithWebBrowser (doesn't matter)?

**Comment by neoxeo** [comment]
@generalloki 

I Have find the problem. I have add this parameter in AlternetUI.csproj "<GeneratePackageOnBuild>True</GeneratePackageOnBuild>"
to generate a nuget package of AlternetUI when it build solution, to use this nuget pacage as local.

If I switch it to False, problem is not present. I don't understand why.

**Comment by generalloki** [comment]
@neoxeo , I build nugets like is described in STEP 6 of readme.md, so I have no idea what is wrong with your approach.
