### ISSUE TITLE
PropertyGrid Sample errors 

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#58]
Impressive job on this part, congratulations !

Version : 4959577ac203e572ab2e6ecaacfae16fc2e3380e
OS : Windows 11

I found some errors, here is a first list : 

When click on PanelTreeAndCards : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/0b742656-10fe-4ac4-a821-058343b347fd)

Same thing with PanelRichTextBox : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/97dcbc1e-15dc-4a57-8061-36ca234b5a05)

For Border : 
BackgroundColor don't change when you select a new color
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/dca6307e-55de-4ae8-9b01-99e09d55c596)

**Comment by generalloki** [comment]
@neoxeo , Thanks! I have updated master with the new version. Exceptions in PropertyGridSample are fixed. As to Border, color is not changed as Background property is also set. I will think on how to make it easier to understand that both Background and BacgkroundColor affect painting.
