### ISSUE TITLE
Add .Net 8.0

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#59]
@generalloki 

.Net 8.0 is now officially released. It  is the new Long Time Support and replace .Net 6.0.

I have test AlternetUi with RC1, RC2 and official release : all tests are OK.

Thanks

**Comment by generalloki** [comment]
@neoxeo 

Thanks for the note! We have updated master with net 8.0 support added. As I said previously right after net 8 release.
