### ISSUE TITLE
Error with BackgroundStyle in PropertyGrid Sample

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#60]
Version : a054324c077236888c6713fff1a6ea02b2fb83a8

In PropertyGrid Sample, there is error on some components when you choose "transparent" : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/4f6a4c9d-c0c4-4ede-9906-2735d71513b7)

**Comment by generalloki** [comment]
@neoxeo , Thanks for the report. Fix uploaded to master.  Now it is not possible to set transparent to BackgroundStyle.

**Comment by neoxeo** [comment]
Thanks a lot. I will test that as soon as I can.
