### ISSUE TITLE
Ideas for Custom components 

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#63]
@generalloki 

Some interesting wpf custom components : 
https://github.com/HandyOrg/HandyControl/tree/master

**Comment by generalloki** [comment]
![Overview](https://github.com/alternetsoft/AlternetUI/assets/59140005/a04614ae-7b3d-4c5f-a491-cf28a7f22f81)

**Comment by generalloki** [comment]
@neoxeo , In any case I have inserted picture of these components to this issue. You started a good topic, we could add here useful links to interesting ideas on what could be implemented in Alternet.UI.

**Comment by generalloki** [comment]
I am closing this issue, but it is still open for the ideas for custom components. The current goal is to port Alternet.Editor, Scripter and Desdigner to Alternet.UI and we will concentrate on these goals.
