### ISSUE TITLE
Ideas of some projects to convert to AlternetUI

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#65]
@generalloki 

https://github.com/Mapsui/Mapsui

**Comment by generalloki** [comment]
@neoxeo , I doubt this will be even considered before UI 1.0 release. Anyway we will come back to this later and make a decision.

**Comment by neoxeo** [comment]
@generalloki 

No problem, this is just a post to share ideas. This project can use Maui, Wpf, Avalonia, Eto... And I thought it would be interesting to add AlternetUI to promote it and show that AlternetUI can be a good choice.

**Comment by generalloki** [comment]
I am closing this issue, but it is still open to the links to other projects and propositions.
