### ISSUE TITLE
Paint Sample error

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#67]
@generalloki 

Version : 4764d6dfa54a38e88782dbf877691f3f9cbe24b7

Open PaintSample
File --> Open --> love-text-free-png-image.png
Click on Action --> Gen Sample Image
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/361527bc-2c47-4442-bb9b-a0241087b83b)

**Comment by generalloki** [comment]
@neoxeo , Thanks! Fixed in master
