### ISSUE TITLE
Easy way to create a new project using the last commited version

### ISSUE THREAD

**Issue by generalloki** [alternetsoft/AlternetUI#68]
A great question from @neoxeo:

Can you tell me, please, what is the easy way to create a new project using the last commited version of each "components" from a template ?

----

We decided to respond here. There will be at least two solutions for that. One is quick which require copy and paste, and one is correct using console command. The task is the following: to have the easy way to create custom project using latest components version from master like we have with nuget.  There we have a command  for that:
 <b>dotnet new alternet-ui</b>

 We are working on the solution and will post here any updates on this issue.

**Comment by generalloki** [comment]
I have uploaded first version of the template to 
https://github.com/alternetsoft/AlternetUI/tree/master/Install.Scripts/MinMasterTemplate

This is minimal project template to use with Alternet.UI latest master version from github.

Limitations:

- You need to edit MinMaster.csproj file and change "AlternetUISourcePath" property to the path where Alternet.UI Source folder is located.
- Uixml forms are not supported by this template. You need to create forms and controls from code. See MainWindow.cs for an example.

I will update this issue when we have an improved template.

**Comment by neoxeo** [comment]
Thanks a lot ! 

I will test this very quickly and give you result.

**Comment by neoxeo** [comment]
@generalloki 

I have tested using MinMasterTemplate with this project (code is not clean but this is not the goal for this moment) : 
[ASCII_Art3.zip](https://github.com/alternetsoft/AlternetUI/files/13539913/ASCII_Art3.zip)

You need to edit MinMaster.csproj file and change "AlternetUISourcePath" property to the path where Alternet.UI Source folder is located.
You need to open project with VS2022, save it and run "run.bat" and open again. Else it doesn't compile into VS2022. 

But this is a good starting point !!!

**Comment by generalloki** [comment]
@neoxeo , Thanks for the feedback on this issue. I have updated MinMaster template and instructions for it.
So, now they are:

## How to use:

- STEP 1. Edit MinMaster.csproj file in Notepad and change "AlternetUIPath" property
to the path where Alternet.UI folder is located.
- STEP 2. Run build.bat.
- STEP 4. Open MinMaster.csproj is Visual Studio and enjoy.

And I have seen your Mario ascii art :)

**Comment by neoxeo** [comment]
@generalloki 

I work on a script to create a new project (UI or Console) from scratch using latest version of AlternetUI development. 

I hope to finish it before this end of this week.

I will publish it hete as soon it is available.

**Comment by neoxeo** [comment]
@generalloki 

Here is the first release of script to create a new  AlternetUI project from scratch using latest version of AlternetUI development : 
[MinMasterTemplateNew.zip](https://github.com/alternetsoft/AlternetUI/files/13724484/MinMasterTemplateNew.zip)

This zip need to be uncompress into Install.Scripts folder.

Launch it, enter informations, wait and open your new project !

**Comment by generalloki** [comment]
I doubt I will be using this project, I prefer "Copy and paste" approach. For now I added a link to this issue in the  readme.md
of MinMaster folder. Like this:

- You can comment or add bug report for MinMaster template here:
https://github.com/alternetsoft/AlternetUI/issues/68
- There is an improved template project created by @neoxeo.
It has script file that asks for project name, path. etc.
https://github.com/alternetsoft/AlternetUI/issues/68#issuecomment-1864016068

**Comment by neoxeo** [comment]
@generalloki 

OK, thanks.

The most important part of the script is how you can create the 2 Nuget packets for AlternetUI/AlternetUI.PAL, on the fly, with the latest comit posted on github and use these packages locally with the NuGet.config file.

**Comment by generalloki** [comment]
@neoxeo , Now when you pointed on this I understand that this is useful - to create nuget on the fly. I will think on how this could be integrated. Maybe even in the main solution, we could have such project or script, so it will be possible to click it to run and to build nuget with the latest source.

**Comment by generalloki** [comment]
For now I am closing this issue, as there are many other more important things to do. The official way is to use nuget. Also there is MinMaster project and solution from neoxeo which is mentioned above.

**Comment by generalloki** [comment]
@neoxeo, 

I have used your idea with local nugets in \Source\Tests\UseLocalPackages\  project. If copy UI nugets into LocalPackages subfolder, project will use them. This was useful for debug nugets. Thanks!

**Comment by neoxeo** [comment]
@generalloki 

Yes I have seen, good news ! Thanks

I have created a powershell script to update an existing project using LocalPackages folder to use the last version of of AlternetUI available (I rebuild nuget packages on the fly and replace current packages present in project with the lastest). I continue tests and post it when I will finish it.

**Comment by generalloki** [comment]
@neoxeo 

I have uploaded new version of Install.Scripts\MinMasterTemplate.
Now it supports uixml forms.
