### ISSUE TITLE
Error with Install.OnlyDebug.bat script

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#69]
@generalloki 

Commit version : 144b44c1d94a985e93a5b3510fdb322202648f3c

Thanks for this script, it is very usefull, but there are some errors : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/cfd84091-a30e-41b4-b54d-ec8b7b5882f5)

**Comment by generalloki** [comment]
@neoxeo, Currently usage of this script is the following: 

- First you run Install.bat (or sh)
- All second runs you run Install.Debug.bat (or sh). 

In this way it works fine. I will post an update here when Install.Debug is improved to work fine without such limitation.

**Comment by generalloki** [comment]
For now I am closing this issue, as Install.OnlyDebug.bat is mostly internal thing and there are many other more important things to fix.
