### ISSUE TITLE
Problem with WebBrowser.NavigateToString()

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#71]
@generalloki 

Version : 0f81a342224beaa98e73088392fab971b763c9f6
  ```
  private void loadWebBrowser()
    {
        string html = "<html><body><h1>Sample HTML File</h1><p>First Sample paragraph.</p><p>Second Sample paragraph.</p></body></html>";
        webBrowser1.NavigateToString(html);
    }
```

**Error :** 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/393eb985-320b-48d0-9340-89852f933945)

**Comment by neoxeo** [comment]
@generalloki 

Version : 3298e9d8f0776af1ce72f5de32e104fa6c589640

This issue seems not to be fixed for me : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/0a318357-c956-4172-88ce-309519dfd9c6)

**Comment by generalloki** [comment]
@neoxeo, Could you please attach the full project with the problem? Also copy/paste error text so I could translate it to English? I have checked the problem in ControlsTest project (test action "Navigate To String") and it works fine. Also is it IE or Edge?

**Comment by neoxeo** [comment]
@generalloki 

Sorry, yes.

Here is error in english  : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/d29cf138-a078-4985-978c-5a01eb5ffe01)

`System.AccessViolationException : 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

Here is a testproject to reproduce error : 
[testWebBrowser.zip](https://github.com/alternetsoft/AlternetUI/files/13778656/testWebBrowser.zip)

**Comment by generalloki** [comment]
I run project from testWebBrowser.zip and it's fine.
Used cmd: dotnet run --framework net8.0

![image](https://github.com/alternetsoft/AlternetUI/assets/59140005/884c7280-7e58-407d-a5a7-9a8110df7346)

So something could be with your Edge installation. Try to use IE backend. This call sets desired backend version WebBrowser.SetBackend(WebBrowserBackend value)

**Comment by neoxeo** [comment]
@generalloki 

I will test this quickly. Strange thing is that navigate url works fine

**Comment by neoxeo** [comment]
@generalloki 

Same error with this code : 
```
private void button1_Click(object? sender, EventArgs e)
{
    // webBrowser1 load local html file
    string html = "<html><body><h1>Sample HTML File</h1><p>First Sample paragraph.</p><p>Second Sample paragraph.</p></body></html>";
    //webBrowser1.Navigate("https://google.com");
    webBrowser1.NavigateToString(html);
}
```

**Comment by neoxeo** [comment]
@generalloki 

After clean .nuget cache and generate new nuget packages with latest version, all works fine with Edge and IE.

I don't know what is the reason of error but now it is solve. Sorry.
