### ISSUE TITLE
GenericImage RotateHue seems not works

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#78]
@generalloki 

RotateHue seems not works.

Test code : 
```
GenericImage test = new GenericImage(new FileStream(@"d:\downloads\starwars_PNG41.png", FileMode.Open));
test.RotateHue(0.5);
pictureBox2.Image = (Image)test; 
```

Image is same as source (but with different color), not rotate

**Comment by generalloki** [comment]
RotateHue - Rotates the hue of each pixel in the image by angle , which is a double in the range of -1.0 to +1.0, where -1.0 corresponds to -360 degrees and +1.0 corresponds to +360 degrees.

So I beleive it works as expected. RotateHue - changes pixel color, not rotates the image

**Comment by neoxeo** [comment]
You are right, sorry for this false issue. I need to take more time and read "describe" before to open an issue.
