### ISSUE TITLE
Error with Install.sh

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#81]
@generalloki 

Version : 21cc50ba11e11fa610eec799e5eb96673456d2e7

OS : Ubuntu 22.04.3 LTS

Error : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/47a34030-c98e-4678-ba31-b16d32a64f1a)

`usr/share/dotnet/sdk/8.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/home/neo56/Dev/AlternetUI/Source/Samples/ControlsSample/ControlsSample.csproj] [/home/neo56/Dev/AlternetUI/Source/Build/Alternet.UI.Pal/Alternet.UI.Pal.proj]`

**Comment by generalloki** [comment]
Fixed in Master

**Comment by neoxeo** [comment]
Test OK.

Thanks
