### ISSUE TITLE
PrpertyGridSample Problems

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#82]
@generalloki 

Version : d2dd6849912408831e59c899a8a2c2e3ed10bcf4

OS : Ubuntu 22.04.3 LTS

In PropertyGridSample, it will be interesting to sort components (A to Z)

In PropertyGridSample, for GenericLabel, if you check or uncheck "HasBorder" nothing change
In PropertyGridSample, for Button, if you check "HasBorder" picture disappear
In PropertyGridSample, for Panel if you check or uncheck "HasBorder" nothing change
In PropertyGridSample, for SpeedButton : 
          - if you check or uncheck "HasBorder" nothing change
          - "Text" property is not used
In PropertyGridSample, for RichTextBox : 
         - it will be interesting to add rich text into box
         - if you add test manually and check "HasBorder" text disappear

In PropertyGridSample, for RadioButton if you check or uncheck "IsChecked" nothing change
In PropertyGridSample, for Border, GenericToolBar, SplittedPanel, Calendar, ColorPicker, CardPanel, DateTimePicker, HorizontalStackPanel , ListBox, ListView, NumericUpDown, Panel, PanelOKCancelButton, ProgressBar, FindReplaceControl, Slider, Scrollbar, StackPanel, TreeView , VerticalStackPanel if you add text in "Text" Properties, nothing change

In PropertyGridSample, for SaveFileDialog, Title not present/visible

Why some Controls don't have HasBorder like CardPanel, CheckBox, HorizontalStackPanel, RadioButton, FindReplaceControl...

**Comment by generalloki** [comment]
I have separated issues into list for the convenience:

OS : Ubuntu 22.04.3 LTS

- IDEA In PropertyGridSample, it will be interesting to sort components (A to Z)
- In PropertyGridSample, for GenericLabel, if you check or uncheck "HasBorder" nothing change
- In PropertyGridSample, for Button, if you check "HasBorder" picture disappear
- In PropertyGridSample, for Panel if you check or uncheck "HasBorder" nothing change
- In PropertyGridSample, for SpeedButton : if you check or uncheck "HasBorder" nothing change, 
- In PropertyGridSample, for SpeedButton : "Text" property is not used
- In PropertyGridSample, for RichTextBox : it will be interesting to add rich text into box
- In PropertyGridSample, for RichTextBox : if you add test manually and check "HasBorder" text disappear
- In PropertyGridSample, for RadioButton if you check or uncheck "IsChecked" nothing change
- In PropertyGridSample, for Border, GenericToolBar, SplittedPanel, Calendar, ColorPicker, CardPanel, DateTimePicker, HorizontalStackPanel , ListBox, ListView, NumericUpDown, Panel, PanelOKCancelButton, ProgressBar, FindReplaceControl, Slider, Scrollbar, StackPanel, TreeView , VerticalStackPanel if you add text in "Text" Properties, nothing change
- In PropertyGridSample, for SaveFileDialog, Title not present/visible
- Why some Controls don't have HasBorder like CardPanel, CheckBox, HorizontalStackPanel, RadioButton, FindReplaceControl

**Comment by generalloki** [comment]
Splitted to #97, #98, #99, #100
Other fixed.
