### ISSUE TITLE
WindowPropertiesSample Problem 

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#84]
@generalloki

Version : d2dd6849912408831e59c899a8a2c2e3ed10bcf4

OS : Ubuntu 22.04.3 LTS

HasTitleBar seems not work, you can check or uncheck, nothing change.

**Comment by generalloki** [comment]
You need to turn off other props additionally to HasTitleBar. I beleive to turn off system menu, close and possibly  maximize, minimize. Play with the props in the demo to find a correct set of props. I beleive we could improve behavior in the next builds, I will post here an update.

**Comment by neoxeo** [comment]
@generalloki 

OK, I will try that.

**Comment by generalloki** [comment]
I have found that under some Linux version title bar disapears only when HasBorder = false. I am closing this issue asoperating system decides what to do, we just pass there property values.
