### ISSUE TITLE
Expanding a Control in a vertical stack panel?

### ISSUE THREAD

**Issue by Shadowblitz16** [alternetsoft/AlternetUI#87]
I didn't know where to make this issue.
A discussions tab would probably be good

Anyways Dock=Fill is not working in vertical stack panel
```
<Window xmlns="http://schemas.alternetsoft.com/ui/2021"
        xmlns:x="http://schemas.alternetsoft.com/ui/2021/uixml"
        x:Class="SMBX_R.MainWindow"
        Title="SMBX_R">
        <Window.Menu>
                <MainMenu>
                        <MenuItem Text="_File">
                                <MenuItem Text="_Open" Name="OpenMenuItem" Click="OpenMenuItemClick" Shortcut="Ctrl+O"/>
                                <MenuItem Text="_Save" Name="SaveMenuItem" Click="SaveMenuItemClick" Shortcut="Ctrl+S"/>
                                <MenuItem Text="_Save As..." Name="SaveAsMenuItem" Click="SaveAsMenuItemClick"/>
                                <MenuItem Text="-"/>
                                <MenuItem Text="E_xit" Name="exitMenuItem" Click="ExitMenuItemClick" />
                        </MenuItem>
                        <MenuItem Text="_Edit">
                                <MenuItem Text="Undo" Name="UndoMenuItem" Click="UndoMenuItemClick" Shortcut="Ctrl+Z"/>
                                <MenuItem Text="Redo" Name="RedoMenuItem" Click="RedoMenuItemClick" Shortcut="Ctrl+Y"/>
                                <MenuItem Text="-"/>
                                <MenuItem Text="Cut" Name="CutMenuItem" Click="CutMenuItemClick" Shortcut="Ctrl+X"/>
                                <MenuItem Text="Copy" Name="CopyMenuItem" Click="CopyMenuItemClick" Shortcut="Ctrl+C"/>
                                <MenuItem Text="Paste" Name="PasteMenuItem" Click="PasteMenuItemClick" Shortcut="Ctrl+V"/>
                                <MenuItem Text="Delete" Name="DeleteMenuItem" Click="DeleteMenuItemClick" Shortcut="Ctrl+Del"/>
                        </MenuItem>
                </MainMenu>
        </Window.Menu>
        <VerticalStackPanel Dock="Fill">
                <Control UserPaint="true" BackColor="Black" Dock="Fill"/>
                <Grid Name="Blocks">
                        <GroupBox>
                                <Grid Name="Grass">
                                        <Button MinWidth="32" MinHeight="32"/>
                                </Grid>
                        </GroupBox>
                </Grid>
                <Panel>
                        <HorizontalStackPanel>       
                                <Button Name="SelectTool" Text="Select"/>
                                <Button Name="EraseTool" Text="Erase"/>
                                <Button Name="BlockTool" Text="Blocks"/>
                                <Button Name="BgosTool" Text="Bgos"/>
                                <Button Name="NpcsTool" Text="Npcs"/>
                                <Button Name="WarpsTool" Text="Warps"/>
                                <Button Name="LiquidsTool" Text="Liquids"/>
                                <Button Name="SettingsTool" Text="Settings"/>
                        </HorizontalStackPanel>
                </Panel>
        </VerticalStackPanel>
</Window>

```

**Comment by generalloki** [comment]
Currently Control.Dock works only in LayoutPanel. I am working on a new layout mechanism (in which Control.Dock will be supported in all containers) and will post here an update when it is ready. For now, If you want to stretch child control of a VerticalStackPanel, assign it's VerticalAlignment = VerticalAlignment.Stretch.

**Comment by generalloki** [comment]
I see you are using Grid control. In order to setup it properly, children of the grid must have ColumnIndex, RowIndex. And Grid itself must be initialized with RowCount and ColumnCount, or with Row and Column collections. See our samples with Grid control.

**Comment by Shadowblitz16** [comment]
ok thankyou

**Comment by Shadowblitz16** [comment]
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/3de4aa8b-28f3-493f-9314-074dee2b7b38)
Stretch is already the default.

And it's not working.
![image](https://github.com/alternetsoft/AlternetUI/assets/2453707/08511f07-2d52-4f64-95c4-06f0aaee4287)

Any ideas?

**Comment by generalloki** [comment]
I beleive in 0.9.505 there is AllowStretch property in StackPanel. Set it True to have Control with VerticalAlignment="Stretch" stretched vertically.
But in the new (not yet released) builds we removed this property and added VerticalAlignment.Fill which will do the job.
I will post here a note when new build with improved layout mechanism is available.

**Comment by Shadowblitz16** [comment]
@generalloki is the kubuntu one you made for me the new release or the old one?

**Comment by generalloki** [comment]
@Shadowblitz16 

You can use this project
Install.Scripts\MinMasterTemplate\ 
as a template for projects which use latest Master version of the Alternet.UI.
There is a readme.md with the instructions.

Also I have added there a sample of expanding a control to fill it's container. See logListBox control...

I beleive we could close this issue

**Comment by generalloki** [comment]
You don't need to copy Bin and Obj from MinMaster

- Get latest Master from github
- Copy  Install.Scripts\MinMasterTemplate\ to an empty folder where your project will be contained.

From readme.md of MinMaster:
- STEP 1. Edit MinMaster.csproj file in the Notepad and change "AlternetUIPath" property
to the path where Alternet.UI folder is located.
- STEP 2. Run build.bat (or build.sh).
- STEP 4. Open MinMaster.csproj is Visual Studio and enjoy.

In MinMaster sample main form shows Fill aligned ListBox control

**Comment by Shadowblitz16** [comment]
ok thankyou

**Comment by Shadowblitz16** [comment]
@generalloki is there a way you can build this under nuget as a preview?

It would be much easier for me to update the nuget package rather then building the MinMasterTemplate project.
Then you can use non prerelease for stable versions.

**Comment by Shadowblitz16** [comment]
I reported it as a separate issue.
