### ISSUE TITLE
Help to convert Winforms to AlternetUI

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#89]
@generalloki 

Is there equivalent to : 
_WndProc(ref Message m)
SendKeys.Send("^v");
TextBox1.SelectionStart
TextBox1.SelectionLength
Screen 
Screen.AllScreens
Graphics.CopyFromScreen_

How to update text in  _mForm1.TextBox.Text from an "external" class ?

Thanks

**Comment by generalloki** [comment]
WndProc(ref Message m) - No, it's not crossplatform. What for? We need to speak about each individual situation here.

Graphics.CopyFromScreen - No. I beleive this is unsecure. 

TextBox1.SelectionStart, TextBox1.SelectionLength. There is GetSelectionStart(), GetSelectionEnd(). But I beleive there should be
SelectionStart, SelectionLength. I will add these. 

Screen - We have it, called Display. But probably Screen also need to be added.
Screen.AllScreens - it is possible to implement it with Display.

SendKeys.Send("^v"); - I beleive it's possible to implement but we need to investigate this.

**Comment by neoxeo** [comment]
@generalloki 

Thanks a lot to have taken time to answer. It's clear for me. 

Have a good day !

**Comment by neoxeo** [comment]
@generalloki 

And for this question please : 
How to update text in other window like _mForm1.TextBox.Text from an "external" class ?

**Comment by generalloki** [comment]
add property

```csharp
public string TextBoxText
{ 
get => textBox.Text;
set => textBox.Text = value; 
}
```
or even:

```csharp
public TextBox TextBox
{ 
get => textBox;
}
```

**Comment by neoxeo** [comment]
@generalloki 

When I see your answer, I'm ashamed to have asked the question, sorry.

Thanks.

**Comment by neoxeo** [comment]
Reaplce by issues 94, 95  and 96

**Comment by neoxeo** [comment]
> Graphics.CopyFromScreen

@generalloki 

I don't understand why you thougth Graphics.CopyFromScreen is unsecure. It is present in standard .Net8.0 and this is not a problem. If someone want to use this to "steal" data he will be able to do that.

**Comment by generalloki** [comment]
There is wxScreenDC in wxWidgets so we could try to add Graphics.CopyFromScreen. 
https://docs.wxwidgets.org/3.2/classwx_screen_d_c.html
By "unsecure" I meant that in new Ubuntu window manager even top window positioning is not possible. So I thought here we potentially can have troubles (it could be unsupported). Anyway I add this as separate issue #113.

**Comment by neoxeo** [comment]
Thank you for these informations. Now, I understand why you speak about "unsecure". Thanks
