### ISSUE TITLE
Add SendKeys

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#95]
@generalloki 

Could you add SendKeys 
(https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys?view=windowsdesktop-8.0)

Thanks

**Comment by generalloki** [comment]
@neoxeo 

BTW If you find SendKeys analogue in WxWidgets I will add this feature much quicker.

**Comment by neoxeo** [comment]
@generalloki 

I will looking for that and give you results.

**Comment by neoxeo** [comment]
@generalloki 

Interesting links : 
Edit: 
https://docs.wxwidgets.org/trunk/classwx_u_i_action_simulator.html
https://github.com/lucassklp/Desktop.Robot/tree/main 
https://github.com/lallousx86/SendKeys

**Comment by generalloki** [comment]
@neoxeo 

Thanks! I beleive I can import wxUIActionSimulator. They write that this class currently doesn't work when using Wayland with wxGTK. But, anyway this would be a simplest solution

**Comment by generalloki** [comment]
Added UIActionSimulator. And example is in 'Samples' page of ControlsSample, 'Action Simulator Sample'. It works ok on Windows and Ubuntu 20.

**Comment by neoxeo** [comment]
@generalloki 

Thanks a lot !

**Comment by neoxeo** [comment]
@generalloki 

I have questions about SendKeys, SendChar and NativeKeyCode and Keys.

Here is my tool to test them : 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/c325c518-2d23-43e6-adb3-ccb00f9f982f)

And project : 
[Tests_SendKeys.zip](https://github.com/alternetsoft/AlternetUI/files/14538664/Tests_SendKeys.zip)

I don't understand why sendchar does not accept "Keys.V" but only "NativeKeyCode"
I don't understand why "simulator.SendKeyDown(NativeKeyCode.ControlV);" doesn't send "CTRL+V"
I don't understand why KeyUp and KeyDown not have same works
SendText have problem when you send text with numbers or special char

**Comment by generalloki** [comment]
Thanks for sending the test project. After studying it:

- Added SendKey which is SendKeyUp+SendKeyDown
- Added NativeKeyCode from 33 to 126, so, for example, NativeKeyCode.V can be used.
- Added Send*If methods, so it is possible to have send command in the single line without if checks.

An example:

```csharp
                        var condition = true;
                        simulator.SendMouseMoveIf(ref condition, button1, (5, 5));
                        simulator.SendMouseClickIf(ref condition);
                        simulator.SendMouseMoveIf(ref condition, editor, (5, 5));
                        simulator.SendMouseClickIf(ref condition);
                        simulator.SendTextIf(ref condition, "Hello");
                        simulator.SendMouseMoveIf(ref condition, button2, (5, 5));
                        simulator.SendMouseClickIf(ref condition);

                        Clipboard.SetText($"({++counter}) Text from clipboard using Ctrl+V");
                        editor2.Focus();
                        editor2.Text = string.Empty;
                        simulator.SendKeyIf(ref condition, NativeKeyCode.V, UIActionSimulator.KeyModifier.Control);
                        return condition;
```

As to your questions: 

- I beleive it is correct to use SendKeyDown and SendKeyUp, not only SendKeyDown. In any case there is new SendKey
- Keys or Key are not accepted by action simulator. It is hard to convert correctly Keys or Key, so for now only NativeKeyCode. In future we might add Send methods with Keys parameter. 
- SendText seems to support only english letters. It's wxWidget, we just passing the call there. In future we might add some code which will improve SendText using calls to SendKey.

The major problem is that Ubuntu 23 and maybe other version is not supported and we can just wait until wxWidget add it's support. 

I will post an update to action simulator on these days and let you know here when it's uploaded.

**Comment by generalloki** [comment]
Update is in Master

**Comment by neoxeo** [comment]
@generalloki 

Thanks a lot for all these new options. I have updated testProject and all work fine, except SendText (but you have explained why) and SendKeyUp. 
![image](https://github.com/alternetsoft/AlternetUI/assets/5283778/67e9fab4-383a-46e2-974d-788955cd0109)

Here is the new TestProject : 
[TestProject2.zip](https://github.com/alternetsoft/AlternetUI/files/14547340/TestProject2.zip)

**Comment by generalloki** [comment]
I beleive SendKeyUp works as expected. You should not use it without SendKeyDown. All controls suppose to receive KeyDown first and only after that KeyUp. So it is better to use SendKey and don't bother with all these.

**Comment by neoxeo** [comment]
Ok, if though that KeyUp should work like down. Now, I will only use SendKey.

Do you want to keep this issue opened to solve Send text when WxWidget fix it ? Else, it can be close.

Thanks.

**Comment by generalloki** [comment]
I beleive we can close it for now, as any improvements in wxWidgets simulator part will be reflected automatically when we switch to new wxWidgets version.
